### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by PrimeTimeTran** [hoangphan159/blog#1]
@Hoang, 
I don't see the Heroku Link to test your application. Please update the readme file with it so I can test. 

Thanks!
Loi

**Comment by PrimeTimeTran** [comment]
@hoangphan159

**Comment by hoangphan159** [comment]
@PrimeTimeTran 

Heroku link has been added. Please check and test it.

Thanks

**Comment by PrimeTimeTran** [comment]
@hoangphan159 ok =)
